/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import VistaVendedor.VistaVendedor;

import Vendedor.Modificar_Guardar;
import static Administrador.Principal.Escritorio;
import Conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author edin1
 */
public class VistaLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista1
     */
    public VistaLogin() {
        initComponents();
    }
    Administrador.VistaAdmin vistaAdmin = new Administrador.VistaAdmin();
    Modificar_Guardar VistaVendedor = new Modificar_Guardar();
    VistaVendedor Vistaven = new VistaVendedor();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jlblContrasena = new javax.swing.JLabel();
        jtflContra = new javax.swing.JTextField();
        jtflUsuario = new javax.swing.JTextField();
        btnIniciarsesion = new javax.swing.JButton();

        jLabel1.setText("POS");

        jlblNombre.setText("Nombre");

        jlblContrasena.setText("Contraseña");

        btnIniciarsesion.setText("Iniiciar sesión");
        btnIniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblContrasena, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtflContra)
                            .addComponent(jtflUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblNombre)
                    .addComponent(jtflUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblContrasena)
                    .addComponent(jtflContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarsesion)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int contador=0;
    private void btnIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarsesionActionPerformed
        try {
            String consulta = "Select nombre,rol from vendedores where nombre='" + jtflUsuario.getText().trim() + "' and password='" + jtflContra.getText().trim() + "'";
            Statement pr = cn.createStatement();
            ResultSet rs = pr.executeQuery(consulta);
            if (rs.next()) {
                if (rs.getInt("rol") == 1) {
                    Escritorio.remove(this);
                    Escritorio.add(vistaAdmin);
                    vistaAdmin.show();
                    vistaAdmin.setVisible(true);
                } else {
                    Escritorio.remove(this);
                    Escritorio.add(Vistaven);
                    Vistaven.show();
                    Vistaven.setVisible(true);
                }

                this.setVisible(false);
                contador = 0;
               // Usuarios.lblUsuario.setText("Usuario: " + rs.getString("usuario"));
            } else {
                if (contador < 2) {
                    contador += 1;
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos", "INCORRECTO", JOptionPane.ERROR_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos", "INCORRECTO", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
            rs.close();
            pr.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        jtflContra.setText("");
        jtflUsuario.setText("");
    }//GEN-LAST:event_btnIniciarsesionActionPerformed

  conexion cc = new conexion();
  Connection cn = cc.Conectar();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarsesion;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblContrasena;
    private javax.swing.JLabel jlblNombre;
    public static javax.swing.JTextField jtflContra;
    public static javax.swing.JTextField jtflUsuario;
    // End of variables declaration//GEN-END:variables
}
